In [2]:
from data_aug.data_aug import *
from data_aug.bbox_util import *
import numpy as np 
import cv2 
import matplotlib.pyplot as plt 
import pickle as pkl
import glob
import pandas as pd
%matplotlib inline

In [11]:
gh=pd.read_csv('gh.csv',index_col='ID')

In [12]:
gh

              x1   y1   x2  y2  c
ID
0low-8.jpeg    4  298  300   3  1
0low-8.jpeg    4  298  300   3  1
0low-8.jpeg    4  298  300   3  1
0low-8.jpeg    4  298  300   3  1
0low-8.jpeg    4  298  300   3  1
0low-8.jpeg    4  298  300   3  1
0low-8.jpeg    4  298  300   3  1
0low-8.jpeg    4  298  300   3  1
0low-8.jpeg    4  298  300   3  1
0low-8.jpeg    4  298  300   3  1
0low-8.jpeg    4  298  300   3  1
0low-8.jpeg    4  298  300   3  1
0low-8.jpeg    4  298  300   3  1
0low-8.jpeg    4  298  300   3  1
0low-8.jpeg    4  298  300   3  1
0low-8.jpeg    4  298  300   3  1
0low-8.jpeg    4  298  300   3  1
0low-8.jpeg    4  298  300   3  1
0low-8.jpeg    4  298  300   3  1
0low-8.jpeg    4  298  300   3  1
0low-8.jpeg    4  298  300   3  1
0low-8.jpeg    4  298  300   3  1
0low-8.jpeg    4  298  300   3  1
10mid-1.jpeg  39  273  270  34  1

In [62]:
bb=np.array(gh.loc[['10mid-1.jpeg'],['x1','x2','y1','y2','c']].to_numpy()).astype('float16')

In [63]:
bb

array([[ 39., 270., 273.,  34.,   1.]], dtype=float16)

In [64]:
file='C:\\Users\Lenovo\Desktop\Downloads\\10mid-1.jpeg'

In [65]:
img=plt.imread(file)

In [66]:
seq0 = Sequence([ Rotate(0)])
seq1 = Sequence([RandomHorizontalFlip(), RandomTranslate(0.13), Rotate(90), RandomShear(0.09)])
seq2 = Sequence([RandomTranslate(0.13), Rotate(90), RandomShear(0.09)])
seq3 = Sequence([RandomHorizontalFlip(), RandomTranslate(0.09), Rotate(180), RandomShear(0.09)])
seq4 = Sequence([RandomTranslate(0.13), Rotate(180), RandomShear(0.09)])
seq5 = Sequence([RandomHorizontalFlip(), RandomTranslate(0.13), Rotate(270), RandomShear(0.09)])
Sequences=[seq0,seq1,seq2,seq3,seq4,seq5]

In [69]:
augmented=pd.DataFrame()
for i,s in enumerate(Sequences):

    img_, bb_ = s(img.copy(), bb.copy())
    path="C:\\Users\Lenovo\Desktop\\augmented\\"+file[34:-5]+'seq'+str(i)+'.jpeg'
    plt.imsave(path,img_)
    dict={'ID':path[34:],'x1':bb_[0][0],'y1':bb_[0][1],'x2':bb_[0][2],'y2':bb_[0][3],'c':bb_[0][4]}
    line=pd.DataFrame(pd.Series(dict)).T
    augmented=pd.concat([augmented,line],ignore_index=True)
augmented.set_index('ID',inplace=True)
augmented.to_csv('augmented.csv')

In [70]:
augmented

                         x1    y1          x2     y2    c
ID
10mid-1seq0.jpeg       39.0  34.0       273.0  270.0  1.0
10mid-1seq1.jpeg   59.80402   0.0  295.223022  232.0  1.0
10mid-1seq2.jpeg   24.40093  37.0  260.601929  271.0  1.0
10mid-1seq3.jpeg  44.666862  50.0  279.167908  286.0  1.0
10mid-1seq4.jpeg   5.732277   6.0  239.800247  242.0  1.0
10mid-1seq5.jpeg        0.0  73.0  232.442627  300.0  1.0